---

- name: Restore de db
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    state: restore
    target: /var/lib/pgsql/{{ version_postgresql }}/backups/{{ item }}.sql
  with_items: "{{ db }}"
  changed_when: false
  become: true
  become_method: su
  become_user: postgres

...
