#URL de repositorio postgressql
url_repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm


#version de postgresql que se instalará
version_postgresql: 15

#paquetes a instalar
paquetes:
  - postgresql{{ version_postgresql }}-server
  - python3-psycopg2
