---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    db: [ "db_1", "db_2", "db_3" ]
  tasks:
#  - name: Example assertion
#    ansible.builtin.assert:
#      that: true

   - name: Comprobar ficheros copia de seguridad
     ansible.builtin.stat:
       path: /tmp/{{ item }}.sql
     register: fichero_copia
     with_items: "{{ db }}"


   - name: Existe fichero
     ansible.builtin.assert:
       that: item.stat.exists == True
       success_msg: "El fichero {{ item.stat.path }} existe, se ha realizado la copia de seguridad"
       fail_msg: "El fichero {{ item.stat.path }} NO existe, NO se ha realizado la copia de seguridad"
     with_items: "{{ fichero_copia.results }}"
